import type { Menu } from "@/types/Menu";

export const menuData: Menu[] = [
	{
		id: 1,
		title: "Inicio",
		newTab: false,
		path: "/",
	},
	{
		id: 2,
		title: "Novedades",
		newTab: false,
		path: "/tienda?sort=newest",
	},
	{
		id: 3,
		title: "Teléfonos",
		newTab: false,
		path: "/tienda?category=smartphone",
		submenu: [
			{
				id: 301,
				title: "— Nuevo —",
				newTab: false,
				path: "/tienda?category=smartphone&condition=new",
			},
			{
				id: 302,
				title: "Apple iPhone",
				newTab: false,
				path: "/tienda?brand=Apple&category=smartphone",
			},
			{
				id: 303,
				title: "Samsung",
				newTab: false,
				path: "/tienda?brand=Samsung&category=smartphone",
			},
			{
				id: 304,
				title: "Xiaomi",
				newTab: false,
				path: "/tienda?brand=Xiaomi&category=smartphone",
			},
			{
				id: 305,
				title: "Oppo",
				newTab: false,
				path: "/tienda?brand=Oppo&category=smartphone",
			},
			{
				id: 306,
				title: "Realme",
				newTab: false,
				path: "/tienda?brand=Realme&category=smartphone",
			},
			{
				id: 307,
				title: "OnePlus",
				newTab: false,
				path: "/tienda?brand=OnePlus&category=smartphone",
			},
			{
				id: 308,
				title: "Honor",
				newTab: false,
				path: "/tienda?brand=Honor&category=smartphone",
			},
			{
				id: 309,
				title: "Motorola",
				newTab: false,
				path: "/tienda?brand=Motorola&category=smartphone",
			},
			{
				id: 310,
				title: "Google Pixel",
				newTab: false,
				path: "/tienda?brand=Google&category=smartphone",
			},
			{
				id: 311,
				title: "Nothing",
				newTab: false,
				path: "/tienda?brand=Nothing&category=smartphone",
			},
			{
				id: 312,
				title: "Nokia",
				newTab: false,
				path: "/tienda?brand=Nokia&category=smartphone",
			},
			{
				id: 313,
				title: "— Seminuevo —",
				newTab: false,
				path: "/tienda?category=smartphone&condition=like_new",
			},
			{
				id: 314,
				title: "Apple (Seminuevo)",
				newTab: false,
				path: "/tienda?brand=Apple&category=smartphone&condition=like_new",
			},
			{
				id: 315,
				title: "Samsung (Seminuevo)",
				newTab: false,
				path: "/tienda?brand=Samsung&category=smartphone&condition=like_new",
			},
			{
				id: 316,
				title: "Xiaomi (Seminuevo)",
				newTab: false,
				path: "/tienda?brand=Xiaomi&category=smartphone&condition=like_new",
			},
			{
				id: 317,
				title: "Tablets",
				newTab: false,
				path: "/tienda?category=tablet",
			},
		],
	},
	{
		id: 4,
		title: "Accesorios",
		newTab: false,
		path: "/tienda?category=fundas_protectores",
		submenu: [
			{
				id: 401,
				title: "Fundas y Protectores",
				newTab: false,
				path: "/tienda?category=fundas_protectores",
			},
			{
				id: 402,
				title: "Smartwatch",
				newTab: false,
				path: "/tienda?category=smartwatch",
			},
			{
				id: 403,
				title: "Auriculares y Altavoces",
				newTab: false,
				path: "/tienda?category=auriculares",
			},
			{
				id: 404,
				title: "Cargadores y Cables",
				newTab: false,
				path: "/tienda?category=cargadores_cables",
			},
			{
				id: 405,
				title: "Power Bank",
				newTab: false,
				path: "/tienda?category=power_bank",
			},
			{
				id: 406,
				title: "Gadgets",
				newTab: false,
				path: "/tienda?category=gadgets",
			},
			{
				id: 407,
				title: "Accesorios Ordenador",
				newTab: false,
				path: "/tienda?category=accesorios_ordenador",
			},
			{
				id: 408,
				title: "Movilidad",
				newTab: false,
				path: "/tienda?category=movilidad",
			},
			{
				id: 409,
				title: "Bolsos y Mochilas",
				newTab: false,
				path: "/tienda?category=bolsos_mochilas",
			},
		],
	},
	{
		id: 5,
		title: "Guess",
		newTab: false,
		path: "/tienda?category=guess",
		submenu: [
			{
				id: 501,
				title: "Fundas Guess iPhone",
				newTab: false,
				path: "/tienda?category=guess&brand=Guess&q=funda+iphone",
			},
			{
				id: 502,
				title: "Fundas Guess Samsung",
				newTab: false,
				path: "/tienda?category=guess&brand=Guess&q=funda+samsung",
			},
			{
				id: 503,
				title: "Bolsos Guess",
				newTab: false,
				path: "/tienda?category=guess&q=bolso",
			},
			{
				id: 504,
				title: "Auriculares Guess",
				newTab: false,
				path: "/tienda?category=guess&q=auriculares",
			},
			{
				id: 505,
				title: "Fundas Airpods Guess",
				newTab: false,
				path: "/tienda?category=guess&q=airpods",
			},
			{
				id: 506,
				title: "Colgantes Guess",
				newTab: false,
				path: "/tienda?category=guess&q=colgante",
			},
			{
				id: 507,
				title: "Cargadores Guess",
				newTab: false,
				path: "/tienda?category=guess&q=cargador",
			},
		],
	},
	{
		id: 6,
		title: "Contacto",
		newTab: false,
		path: "/contact",
	},
];
